[Feature] 소셜 로그인 구현
jisung-in/backend pull request #11
Opened 2024-03-17 11:28 UTC by pdohyung

## 💡 연관된 이슈
close #1  

## 📝 작업 내용
- 소셜 로그인 요청 시 해당 서비스 로그인 화면으로 Redirect 하는 기능 구현
   - 현재는 카카오만 가능
- 프론트단에서 넘겨주는 인증 코드로 AccessToken을 발급 받는 기능 구현
   - AccessToken으로 사용자 정보를 가져와서 회원가입 / 로그인 가능

## 💬 리뷰 요구 사항
안녕하세요 ~ 소셜 로그인 관련 첫 PR입니다.
처음에는 스프링 시큐리티를 사용해서 구현하려고 했지만 의존도가 높아지는 것 같아 시큐리티 없이 구현했습니다.
결과적으론 시큐리티에 대한 의존성은 없어졌지만 로직 자체는 조금 복잡해진 것 같습니다.

![image](https://github.com/jisung-in/backend/assets/58456758/591c8c25-37e9-40a9-ae57-59372bf78f75)

일단 프론트단에서 사용자가 로그인 & 정보 제공 동의를 완료하면 인증 서버가 프론트단한테 인증 코드를 보내는 부분이 4번 과정입니다.
4번 Redirect 과정에서 인증 코드를 꺼내서 서버에 인증 코드와 함께  POST 요청을 해야 로직이 수행됩니다.
제가 구현한 부분은 4번 중간부터 구현했다고 보시면 될 거 같습니다.

코드에서 궁금한 점이나 피드백 있으시면 편하게 달아주세요.
또한 블로그 글을 작성했으니 참고하시고 질문 달아주셔도 좋을 것 같아요 👍 
🔥  https://trysolve.tistory.com/25 🔥

2024-03-17 13:25 UTC, jwooo requested changes
WebFlux를 사용해서 비동기로 처리하는 부분은 저도 추후에 적용했어야 하는데 도움이 많이 된거 같습니다!
새로운 개념까지 공부하면서 개발 하시느라 고생하셨습니다!

2024-03-17 13:25 UTC, jwooo commented on src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java
> +@ConfigurationProperties(prefix = "oauth.kakao")
```
@ConfigurationProperties(prefix = "oauth.kakao")
```
`@ConfigurationProperties`를 사용한 특별한 이유가 있을까요? `@Value`로도 설정 파일에 있는 값을 가져올 수 있는 걸로 알고 있어서 사용하신 이유가 있는지 궁금합니다!

2024-03-17 13:25 UTC, jwooo commented on src/main/java/com/jisungin/api/oauth/OauthController.java
> +        return ApiResponse.ok(null);
`ApiResponse.ok(null)`에서 리턴 타입이 `null` 값일 때 사용할 수 있는 `ok()` 메서드를 오버라이딩해서 사용하는 것에 대해 어떻게 생각하시나요?

2024-03-17 14:04 UTC, AHNYUNKI approved these changes
안녕하세요! 도형님!
>처음에는 스프링 시큐리티를 사용해서 구현하려고 했지만 의존도가 높아지는 것 같아 시큐리티 없이 구현했습니다.
결과적으론 시큐리티에 대한 의존성은 없어졌지만 로직 자체는 조금 복잡해진 것 같습니다.

이 부분에서 시큐리티는 보안을 담당하는 프레임워크인걸로 알고있는데, 보안을 담당하는 곳에서 의존성이 높아지면 안되는 이유라도 있을까요? 개인적으로 궁금해서 리뷰 남깁니다!

2024-03-18 06:09 UTC, pdohyung commented on src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java
> +@ConfigurationProperties(prefix = "oauth.kakao")
`@Value`도 외부 설정을 가져올 수 있지만 `@ConfigurationProperties`는 여러 속성을 그룹화하여 가져올 수 있기 때문에 더 편리합니다. 
또한 설정 클래스의 필드를 타입에 맞게 지정할 수 있어서 타입 안정성이 향상되기 때문에 사용했습니다 !

2024-03-18 06:13 UTC, pdohyung commented on src/main/java/com/jisungin/api/oauth/OauthController.java
> +        return ApiResponse.ok(null);
넵 저도 동의합니다.
추후에 같이 논의를 통해 수정하면 좋을듯합니다.

2024-03-18 06:22 UTC, pdohyung commented
> 이 부분에서 시큐리티는 보안을 담당하는 프레임워크인걸로 알고있는데, 보안을 담당하는 곳에서 의존성이 높아지면 안되는 이유라도 있을까요? 개인적으로 궁금해서 리뷰 남깁니다!

좋은 질문인 것 같습니다.
저희는 현재 자체 로그인 없이 소셜 로그인만 구현합니다.
소셜 로그인 서비스는 사용자 인증 자체를 해당 서비스에서 제공하기 때문에 현재는 시큐리티 프레임워크가 필요 없다고 판단했습니다. 
또한 시큐리티에 포함된 OAuth 2.0은 구현할 때 커스터마이징의 한계가 존재하고 직접 구현하는 것에 비해 추상적인 부분이 많다고 느꼈습니다.
결과적으로 현재 코드를 살펴보시면 확장성과 유지 보수성이 좋은 로직이 완성된 것을 확인하실 수 있습니다.
그리고 보안을 위해 추후에 JWT를 적용할 예정입니다.
나중에 같이 논의해보면 좋을듯합니다.

2024-03-18 07:12 UTC, jwooo approved these changes
리뷰 확인 했습니다 👍

2024-03-18 07:12 UTC, jwooo commented on src/main/java/com/jisungin/api/oauth/OauthController.java
> +        return ApiResponse.ok(null);
넵 추후에 다같이 상의 해보시죠!

2024-03-18 07:12 UTC, jwooo commented on src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java
> +@ConfigurationProperties(prefix = "oauth.kakao")
설정파일에서 주입 받아야 할 필드가 많을 때 유용하게 사용할 수 있겠네요. 

추후에 적용할 수 있으면 저도 적용해보겠습니다!

2024-03-18 08:01 UTC, merged