[Feature] 베스트 셀러 Redis 조회 기능 및 스케쥴링 구현
jisung-in/backend pull request #55
Opened 2024-04-01 06:13 UTC by jwooo

## 💡 연관된 이슈
close #45

## 📝 작업 내용
- Redis 설정
- Scheduler 설정
- 베스트 셀러 Redis를 통한 조회 기능 구현
- 베스트 셀러 스케쥴링을 통한 데이터 자동 수정 기능 구현

## 💬 리뷰 요구 사항
`Redis`를 추가하면서 테스트에서 `Redis`를 사용할 수 없는 문제가 발생하여 `TestContainers`를 사용하였습니다. 

`TestContainers`를 사용하면서 까지 `Redis`를 테스트하는 것이 맞을지 아니면 `@MockBean`으로 처리하여 테스트하는 것이 좋을지 고민하고 있습니다. 

어떻게 하는게 좋은 방법인지 몰라 좋은 생각 있으시면 알려주시면 감사하겠습니다 !

2024-04-01 07:48 UTC, AHNYUNKI reviewed
정우님 코드 잘봤습니다!
제가 남긴 리뷰 한 번 보시고 답 주시면 감사하겠습니다!

그리고 정우님이 남기신 질문
>TestContainers를 사용하면서 까지 Redis를 테스트하는 것이 맞을지 아니면 @MockBean으로 처리하여 테스트하는 것이 좋을지 고민하고 있습니다.

이 부분 같은 경우에는 Redis 테스트 시 파이프라인에서 통과하지 못할까봐 `@MockBean` 처리를 하는것이 좋다고 생각이 들었었는데,  정우님이 잘 해결하신거같아, 굳이 `@MockBean`  테스트로 진행하지 않으셔도 될거같습니다!

2024-04-01 07:48 UTC, AHNYUNKI commented on src/main/java/com/jisungin/domain/book/repository/BestSellerRedisRepository.java
> +            throw new RuntimeException(e);
런타임 Exception은 보다는 무슨 Exception인지 명시 해주는게 좋을거 같습니다!! 정우님!

2024-04-01 07:48 UTC, AHNYUNKI commented on src/test/java/com/jisungin/application/service/book/BestSellerServiceTest.java
> +@Slf4j
여기에다가 @SpringBootTest를 다시는거보다 RedisTestContainer 쪽에다 다시는게 좋지않을까요 ? 나중에 TalkRoom에도 Redis를 적용시켜야 할 수도 있는데 서버가 두개 켜지는거보다 한 번 켜지는 편이 더 좋을거같아서 얘기드립니다!

2024-04-01 09:09 UTC, pdohyung requested changes
내용 확인했습니다 !
질문 남겼으니 답변 부탁드립니다. 😊

2024-04-02 11:16 UTC, jwooo commented on src/main/java/com/jisungin/domain/book/repository/BestSellerRedisRepository.java
> +            throw new RuntimeException(e);
앗! 까먹고 수정하지 못했네요..

수정하겠습니다!!

2024-04-02 11:22 UTC, jwooo commented on src/test/java/com/jisungin/application/service/book/BestSellerServiceTest.java
> +@Slf4j
해당 컨테이너는 `Redis` 전용 테스트 컨테이너 입니다. 추후에 `Kafka`나 `PostgreSql`이 추가될 수도 있습니다. 이런 경우 나머지 테스트 컨테이너에도 `@SpringBootTest`를 붙여야 합니다. 

나중에 상속으로 하지 않는 방식으로 구현하여 `ServiceTestSupport`에서 해결할 수 있도록 해보겠습니다!

2024-04-02 11:25 UTC, jwooo commented on src/main/java/com/jisungin/JisunginApplication.java
>  public class JisunginApplication {
네 `@Enablexxx` 어노테이션들은 관련된 라이브러리의 기능을 활성화하는 역할 입니다!

2024-04-02 11:28 UTC, jwooo commented on src/main/java/com/jisungin/config/RedisConfig.java
> +        redisTemplate.setHashValueSerializer(new StringRedisSerializer());
`setKeySerializer()`과 `setValueSerializer()`는 일반적인 키와 값을 저장하는 `RedisTemplate`의 직렬화 방식을 지정하는 데 사용됩니다. 

`redis`에서의 `get`과 `set`의 명령어와 같은 기능을 사용할 때 `String` 타입으로 직렬화 한다는 의미입니다. 

`setHashKeySerializer()`과 `setValueSerializer()`는 `Redis` 해시에 대해 사용됩니다. 저희는 베스트 셀러에 대한 값을 `Hash`로 저장하기 때문에 해당 설정도 추가적으로 적용하였습니다!

2024-04-02 11:29 UTC, jwooo commented on src/main/java/com/jisungin/infra/crawler/Yes24Crawler.java
> +        Map<Long, CrawlingBook> bestSellerBooks = new ConcurrentHashMap<>();
네 `HashMap`으로 구현하였더니 테스트 단계에서 문제가 발생하여 `Thread-safe`한 `ConcurrentHashMap`으로 변경하였습니다!

2024-04-02 11:30 UTC, jwooo commented on src/main/java/com/jisungin/infra/crawler/Yes24Fetcher.java
> +    @Retryable(retryFor = BusinessException.class, maxAttempts = 5, backoff = @Backoff(delay = 1000))
해당 메서드에서 `BusinessException`이 발생하면 5번 재시도 하며 재시도 간의 딜레이는 1초로 설정한 코드입니다!

2024-04-02 12:08 UTC, AHNYUNKI approved these changes
아이고 고생하셨습니다 정우님~~

2024-04-02 12:09 UTC, AHNYUNKI commented on src/test/java/com/jisungin/application/service/book/BestSellerServiceTest.java
> +@Slf4j
네 알겠습니다

2024-04-02 12:23 UTC, pdohyung approved these changes
고생하셨습니다 ! 😊

2024-04-02 12:28 UTC, merged