[Feature] TalkRoom 생성 API 구현
jisung-in/backend pull request #6
Opened 2024-03-15 12:38 UTC by AHNYUNKI

## 💡 연관된 이슈
close #2 

## 📝 작업 내용
* TalkRoom 생성 API 추가
* TalkRoom 생성 API 테스트 코드 추가

## 💬 리뷰 요구 사항
회원 API 도메인이 아직 개발이 되지 않아 회원의 정보를 "user@gmail.com"로 설정하여 기능 및 테스트를 진행하였습니다.
추가적으로 테스트 진행할 내용이 있는지 확인 부탁드립니다!

2024-03-15 12:53 UTC, jwooo requested changes
맨 아래 중괄호 사이 개행문자 넣어주시면 감사하겠습니다!

2024-03-15 12:53 UTC, jwooo commented on src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
> +                .readingStatus(null)
`readingStatus`에 `null`을 넣지 않아도 `null`값이 들어가는데 추가한 특별한 이유가 있을까요?

2024-03-15 12:54 UTC, pdohyung requested changes
수고하셨습니다 !

요구사항 반영해 주시면 될 거 같습니다 ~

2024-03-15 12:54 UTC, pdohyung commented on src/main/java/com/jisungin/domain/ReadingStatus.java
> +    }
독서 상태를 문자열 리스트로 받아서 열거 리스트로 반환하는 로직인가요 ?

그리고 예외 처리를 수정해야 될 거 같습니다 !

2024-03-15 12:58 UTC, AHNYUNKI commented on src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
> +                .readingStatus(null)
다른 리뷰어들이 이해하기 쉽도록, NULL 값이 들어갔다는 걸 명시했습니다!

2024-03-15 12:59 UTC, AHNYUNKI commented on src/main/java/com/jisungin/domain/ReadingStatus.java
> +    }
네네 맞습니다!
수정하도록 하겠습니다~

2024-03-16 03:24 UTC, pdohyung requested changes

2024-03-16 03:24 UTC, pdohyung commented on src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
> +                .orElseThrow(() -> new IllegalArgumentException("책을 찾을 수 없습니다."));
요청 독서 상태가 empty인지 검사하는 책임은 독서 상태 enum에서 처리해야 할 것 같습니다.

밑에 예외 처리 로직도 수정해주세요 ~

2024-03-16 04:13 UTC, AHNYUNKI commented on src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
> +                .orElseThrow(() -> new IllegalArgumentException("책을 찾을 수 없습니다."));
네 확인했습니다~!

2024-03-16 04:33 UTC, pdohyung approved these changes
수정사항 확인했습니다.
디테일한 부분은 추후에 수정하면 될 것 같아요.
수고하셨습니다 !

2024-03-16 05:59 UTC, jwooo commented on src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java
> +                .readingStatus(null)
네 알겠습니다. 좋은 방식인거 같네요!

2024-03-16 06:00 UTC, jwooo approved these changes
수정사항 확인 했습니다!!

2024-03-16 06:02 UTC, merged