[Refactor] TalkRoom 조회 Query 리펙토링
jisung-in/backend pull request #63
Opened 2024-04-05 09:21 UTC by AHNYUNKI

## 💡 연관된 이슈
close #61 

## 📝 작업 내용
*. TalkRoom 조회 API Comment 조회 API 변경
* 조회 메서드 분리
* TalkRoom 서비스 메서드 분리
* Service - Repository 계층 분리

## 💬 리뷰 요구 사항
리뷰 요구 사항은 없습니다.

2024-04-06 06:01 UTC, pdohyung requested changes
수고하셨습니다 !
질문 남겼으니 답변 부탁드립니다. 😊

2024-04-06 06:01 UTC, pdohyung commented on src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
> +        }
해당 if문이 어떤 동작을 하는지 간단하게 설명 부탁드립니다 !

2024-04-06 06:10 UTC, AHNYUNKI commented on src/test/java/com/jisungin/application/comment/CommentServiceTest.java
> +        }
음 저도 처음에 saveAll를 했으나 간혈적으로 저장순서가 바뀌는 문제로 테스트가 실패해서 그냥 포문으로 저장 시켰습니다!

2024-04-06 06:20 UTC, AHNYUNKI commented on src/main/java/com/jisungin/application/talkroom/TalkRoomService.java
> +        }
유저가 토론방을 수정할 때, 새로운 이미지를 추가하고 기존에 있던 이미지를 삭제 할때 if문으로 새로운 이미지 혹은 삭제된 이미지 url이 있는지 체크를 하고 있다면 로직을 수행하도록 했습니다!

2024-04-06 07:03 UTC, pdohyung commented on src/test/java/com/jisungin/application/comment/CommentServiceTest.java
> +        }
제가 알기로 saveAll은 리스트의 순서대로 저장합니다 !
테스트의 다른 부분에서 문제가 발생했던 건 아닐까요 ?

2024-04-06 07:57 UTC, jwooo requested changes
고생하셨습니다!! 리뷰 남겼으니 확인 부탁드립니다!

2024-04-06 07:57 UTC, jwooo commented on src/main/java/com/jisungin/api/SearchRequest.java
> +                .order(order != null ? order : "re")
혹시 정렬 기준에서 "re"를 사용하시는 지 궁금해서 리뷰 남깁니다!

2024-04-06 09:08 UTC, AHNYUNKI commented on src/test/java/com/jisungin/application/comment/CommentServiceTest.java
> +        }
저도 그런걸로 알고있는데 repository 테스트에서 자꾸 테스트 실패가 떴습니다 ㅠㅠ

2024-04-06 09:18 UTC, AHNYUNKI commented on src/main/java/com/jisungin/api/SearchRequest.java
> +                .order(order != null ? order : "re")
정렬 값이 null이 들어올 시 seach.getOrder() 로 가져오게 되면 예외가 발생하기 때문에 null이면 기본으로 최신순으로 정렬하게 하기 위해 짧게 "re" 값으로 넘겨줬습니다!

2024-04-07 09:28 UTC, pdohyung approved these changes
수고하셨습니다 ~ 👍

2024-04-07 09:28 UTC, jwooo commented on src/main/java/com/jisungin/api/SearchRequest.java
> +                .order(order != null ? order : "re")
"re" 값이 불명확한거 같아서 디폴드 값이 무조건 최신순이라면 default나 recent로 값을 넘겨주어도 되지 않을까요?

2024-04-07 09:30 UTC, AHNYUNKI commented on src/main/java/com/jisungin/api/SearchRequest.java
> +                .order(order != null ? order : "re")
나중에 수정하도록 하겠습니다!

2024-04-07 09:30 UTC, jwooo commented on src/main/java/com/jisungin/api/SearchRequest.java
> +                .order(order != null ? order : "re")
넵 알겠습니다!

2024-04-07 09:30 UTC, jwooo approved these changes
수고하셨습니다 👊

2024-04-07 09:31 UTC, merged