[Feature] 내 한줄평 모아보기 API 구현
jisung-in/backend pull request #64
Opened 2024-04-06 06:25 UTC by pdohyung

## 💡 연관된 이슈
close #62 

## 📝 작업 내용
- 내 한줄평(리뷰 내용) 모아보기 API 구현

## 💬 리뷰 요구 사항
추가된 리뷰 내용 조회 쿼리 확인 부탁드립니다 ! 😊

2024-04-06 07:37 UTC, jwooo requested changes
고생하셨습니다 👍

궁금하게 있어 리뷰 남겼으니 확인 부탁드립니다!!!

2024-04-06 07:37 UTC, jwooo commented on src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
> +    }
해당 쿼리는 리뷰에 좋아요를 누른 모든 사용자를 가져와서 계산하는 로직인 거 같습니다. 

혹시 `ReviewContentResponse`에서 나온 `ReviewId`를 가지고 `ReviewLike` 테이블에서 조회하는 방식은 어떻게 생각하시나요? 

```sql
SELECT ReviewLike.Review.id 
FROM ReviewLike
WHERE ReviewLike.Review.id in (ReviewContentResponseIds)
    AND ReviewLike.User.id = (userId)
```

2024-04-07 10:04 UTC, AHNYUNKI reviewed
리뷰 남겼습니다! 답변 부탁드립니다~!

2024-04-07 10:37 UTC, pdohyung commented on src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
> +    }
기존에는 `PageResponse<ReviewContentResponse>`에서 각 `ReviewContentResponse`마다 해당 리뷰를 좋아요한 유저 리스트를 가지고 있었습니다.
정우님이 말씀하신대로 리뷰를 좋아요한 유저가 많아질수록 해당 쿼리는 부담이 될 거 같아요.
그래서 요청한 유저가 좋아요한 review_id 리스트를 반환하는 방식으로 수정했습니다 ! 👊

2024-04-07 10:46 UTC, pdohyung commented on src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
> +        });
`reviewLikeUsers`는 review_id가 key, 해당 리뷰를 좋아요한 유저 리스트가 value인 Map 형태입니다.
그리고 reviewContents 클래스는 좋아요한 유저 리스트 변수가 존재합니다.
그래서 Key가 일치하는 review_content를 찾아서 존재하면, 좋아요한 유저 리스트를 추가해주는 로직입니다.

하지만 각 리뷰마다 좋아요한 사용자가 많아질수록 쿼리에 부담이 될 것 같아서 현재 이 로직은 삭제했습니다.
요청한 사용자가 좋아요한 review_id 리스트를 반환하는 형태로 수정했으니 다시 한번 봐주세요 ! ✊

2024-04-07 11:13 UTC, jwooo commented on src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java
> +    }
넵 확인했습니다!!

2024-04-07 11:13 UTC, jwooo approved these changes
고생하셨습니다 !!

2024-04-07 11:18 UTC, AHNYUNKI approved these changes
고생하셨습니다!!

2024-04-07 11:20 UTC, merged