[Feature] Book 등록 API 구현
jisung-in/backend pull request #9
Opened 2024-03-17 07:53 UTC by jwooo

## 💡 연관된 이슈
close #3 

## 📝 작업 내용
- Book 생성 API 구현
- Book 생성 API 테스트 코드 작성
- Book 엔티티 변경으로 인한 TalkRoom 생성 API 테스트 코드 수정
- 잘못 등록된 ErrorCode 수정

## 💬 리뷰 요구 사항
Book 엔티티에서 `String[]`을 `String`으로 변환하는 로직을 BookCreateRequest로 옮겨 타입 변환의 역할을 해당 객체에게 위임하였습니다.

**Before**
```java
// Book.java
@Builder
private Book(String title, String content, String authors, String isbn, String publisher, String url,
             String thumbnail, LocalDateTime dateTime) {
    this.title = title;
    this.content = content;
    this.authors = Arrays.toString(authors);
    this.isbn = isbn;
    this.publisher = publisher;
    this.url = url;
    this.thumbnail = thumbnail;
    this.dateTime = dateTime;
}
``` 

**After**
```java
// Book.java
@Builder
private Book(String title, String content, String authors, String isbn, String publisher, String url,
             String thumbnail, LocalDateTime dateTime) {
    this.title = title;
    this.content = content;
    this.authors = authors;   // 타입 변환 로직 BookCreateRequest로 이동
    this.isbn = isbn;
    this.publisher = publisher;
    this.url = url;
    this.thumbnail = thumbnail;
    this.dateTime = dateTime;
}

// BookCreateRequest.java
@Builder
private BookCreateRequest(String title, String contents, String url, String isbn, String dateTime, String[] authors,
                          String publisher, String thumbnail) {
    this.title = title;
    this.contents = contents;
    this.url = url;
    this.isbn = isbn;
    this.dateTime = dateTime;
    this.authors = authors;
    this.publisher = publisher;
    this.thumbnail = thumbnail;
}

public BookCreateServiceRequest toServiceRequest() {
    return BookCreateServiceRequest.builder()
            .title(title)
            .contents(contents)
            .url(url)
            .isbn(isbn)
            .dateTime(convertToLocalDateTime(dateTime))
            .authors(convertToString(authors))
            .publisher(publisher)
            .thumbnail(thumbnail)
            .build();
}

private LocalDateTime convertToLocalDateTime(String dateTime) {
    return OffsetDateTime.parse(dateTime, DateTimeFormatter.ISO_OFFSET_DATE_TIME).toLocalDateTime();
}

private String convertToString(String[] authors) {
    return Arrays.toString(authors);
}
```

해당 변경에 대해서 어떻게 생각하시는지 알려주시면 감사하겠습니다!!

2024-03-17 12:15 UTC, pdohyung requested changes
안녕하세요 ! 정우님
남기신 리뷰 사항에 답변드립니다.
> Book 엔티티에서 String[]을 String으로 변환하는 로직을 BookCreateRequest로 옮겨 타입 변환의 역할을 해당 객체에게 위임하였습니다.

저도 Book 엔티티에 저자명은 String으로 설정되어 있기 때문에 배열을 문자열로 변환하는 로직을 엔티티가 가지는 것은 애매하다고 생각합니다.
Book 생성 DTO가 책임을 가지는 것이 더 옳다고 생각하여 해당 변경에 찬성합니다. 👍 

전체적으로 코드를 잘 작성하셔서 딱히 피드백 할 부분이 없네요.
개인적으로 궁금한 부분에 대해서 질문 남겼으니 답변 남겨주세요 !
수고하셨습니다 👍

2024-03-17 12:15 UTC, pdohyung commented on src/test/java/com/jisungin/api/book/BookControllerTest.java
> +    }
저는 보통 테스트하는 컨트롤러와 관련된 로직을 직접 Mock Bean으로 등록해서 테스트합니다.
`@AutoConfigureMockMvc`는 사용해보지 않아서 생소하네요 !
관련된 로직들을 전부 mock bean으로 자동 등록해주는 건가요 ?

2024-03-17 13:58 UTC, AHNYUNKI approved these changes
안녕하세요! 정우님
> Book 엔티티에서 String[]을 String으로 변환하는 로직을 BookCreateRequest로 옮겨 타입 변환의 역할을 해당 객체에게 위임하였습니다.

저도 응답받은 데이터를 엔티티에서 처리하는건 별로 좋지 못하다고 생각이 들어 전적으로 의견에 동의합니다! 
고생하셨습니다~~~

2024-03-17 13:58 UTC, AHNYUNKI commented on src/main/java/com/jisungin/application/book/response/BookResponse.java
> +    private Long id;
ISBN이 도서의 고유번호 일텐데 굳이 Long id을 선언해줄 이유가 있을까요??

2024-03-18 07:38 UTC, jwooo commented on src/main/java/com/jisungin/application/book/response/BookResponse.java
> +    private Long id;
> ISBN이 도서의 고유번호 일텐데 굳이 Long id을 선언해줄 이유가 있을까요??

저도 `id`를 포함해서 리턴 할까 `isbn`만 리턴할까 고민 하였는데 id를  리턴하면 여러가지  장점을 얻을 수 있을 것 같아 `id`를 포함하여 리턴하기로 결정하였습니다. 

`id`를 포함하여 리턴하면 추후에 조회 시 `id` 컬럼은 `@Id`로 등록된 필드이기 때문에 인덱싱을 통한 조회를 통해 성능상의 이점을 받을 수 있습니다. 

그리고 가독성 측면에서도 `isbn` 보다 `id`가 더 좋다고 판단하였습니다. `isbn`은 `xxxxx-xxxxx`와 같은 포멧을 가지고 있지만 `id`는 숫자 값으로 URI를 구성할 수 있기 때문에 가독성이 좋아집니다. 

그렇기에 `BookResponse`에서 `id`값을 추가하여 리턴하였습니다!

2024-03-18 07:55 UTC, AHNYUNKI commented on src/main/java/com/jisungin/application/book/response/BookResponse.java
> +    private Long id;
음! 잘 읽었습니다.
 확실히 조회와 가독성 측면에선 ID값을 명시해주는 것이 좋다고 생각이 드네요! 수고하셨습니다!

2024-03-18 08:00 UTC, jwooo commented on src/test/java/com/jisungin/api/book/BookControllerTest.java
> +    }
> 관련된 로직들을 전부 mock bean으로 자동 등록해주는 건가요 ?

네 맞습니다! `@AutoConfigureMockMvc`는 `Mock Bean`을 자동으로 주입해주는 어노테이션 입니다. 

`MockBean`으로 등록해서 테스트 하는 방식은 `@BeforeEach`에 작성해야 하기 때문에 `Dependency Injection`을 지킬 수 있지만 테스트의 개수만큼 n번 `Mock Bean`을 주입받아야 합니다. 하지만 세부적인 설정을 해야할 때는 `Mock Bean`을 `@BeforeEach`에 정의하여 사용하는 방법도 좋은 방법입니다. 

도형님이 말씀하시는 `Mock`을 사용하는 방식은 추후에 `Spring Rest Docs` 테스트 작성할 때 사용할 거 같아 현재 테스트에서는 컨트롤러 통합 테스트를 확인해보기 위해 `@SpringBootTest`와 `@AutoConfigureMockMvc`를 사용하였습니다.

2024-03-18 08:03 UTC, pdohyung approved these changes

2024-03-18 08:07 UTC, merged